videoapp/posts/urls.py
from django.urls import path
from posts import views

app_name = "posts"

urlpatterns = [
    # Tür seçimi ile create view
    path("create/<str:post_type>/", views.create_post, name="create_post"),
    path("explore/", views.explore, name="explore"),
    path("user/<str:username>/", views.user_posts, name="user_posts"),
    path("post/<int:pk>/", views.post_detail, name="post_detail"),
    path("post/<int:pk>/like/", views.toggle_like, name="toggle_like"),
    path("post/<int:pk>/save/", views.toggle_save, name="toggle_save"),
]

videoapp/users/urls.py
from django.urls import path
from users import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/<str:username>/", views.profile_view, name="profile"),
    path('settings/', views.settings_view, name='settings'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videoapp/videoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include("users.urls")),
    path('posts/', include('posts.urls')),
    path('', index, name="index"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videoapp/templates/partials/footer.html
<footer class="text-center mt-5 py-3 border-top footer">
    <div class="container">
      <p style="margin-top: 20px;" class="mb-0 footer-text">Rıdvan Sezen &copy; 2025 VideoApp - All rights reserved.</p>
      <p style="margin-top: 50px;" class="footer-text">Youtube hesabım : <a href="https://www.youtube.com/@rsensedits"><i style="color: #fff;" class="fa-brands fa-youtube"></i></a></p>
      <p style="margin-top: 30px;" class="footer-text">Instagram hesabım : <a href="https://www.instagram.com/rsensedits/?hl=tr"><i style="color: #fff;" class="fa-brands fa-instagram"></i></a></p>
    </div>
  </footer>
  

videoapp/templates/partials/navbar.html
{% load static %}
{% get_media_prefix as MEDIA_URL %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand navbar-link-texts" href="{% url 'index' %}">VideoApp</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link navbar-link-texts" aria-current="page" href="{% url 'index' %}">Anasayfa</a>
          </li>
          <li class="nav-item">
            <a class="nav-link navbar-link-texts" href="{% url 'posts:explore' %}">Keşfet</a>
          </li>
          <li class="nav-item">
            <a class="nav-link navbar-link-texts" aria-disabled="true">Disabled</a>
          </li>
        </ul>

        
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% if request.user.is_authenticated %}
              <!-- Kullanıcı giriş yapmışsa -->
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      <img src="{% if request.user.profile_picture %}{{ request.user.profile_picture.url }}{% else %}{{ MEDIA_URL }}default.jpg{% endif %}" 
                      alt="Profil" class="rounded-circle" width="35" height="35" style="object-fit: cover;">
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end">
                      <li class="dropdown-header">
                          {{ request.user.username }}
                          {% if request.user.is_verified %}
                            <i class="fa-solid fa-circle-check text-primary ms-1" title="Doğrulandı" aria-hidden="true"></i>
                          {% endif %}
                          {% if request.user.username == "ridvan" %}
                              <span class="text-danger ms-1">(admin)</span>
                          {% endif %}
                      </li>
                      <li><hr class="dropdown-divider"></li>
                      <li>
                          <a class="dropdown-item" href="{% url 'users:profile' request.user.username %}">Profil</a>
                      </li>
                      <li>
                        <a class="dropdown-item" href="{% url 'users:settings' %}">Ayarlar</a>
                      </li>
                      <li>
                          <a class="dropdown-item" href="{% url 'users:logout' %}">Çıkış yap</a>
                      </li>
                  </ul>
              </li>
          {% else %}
              <!-- Kullanıcı giriş yapmamışsa -->
              <li class="nav-item">
                  <a class="nav-link navbar-link-texts" href="{% url 'users:register' %}">Kayıt ol</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link navbar-link-texts" href="{% url 'users:login' %}">Giriş yap</a>
              </li>
          {% endif %}
        </ul>
        
      </div>
    </div>
  </nav>